import { ref } from 'vue'
export const PRODUCTS_DATA = ref([
	{
		products: [
			{
				id: 'p6',
				count: 0,
				name: 'Apple iPhone 15 Pro Titanium 128 Gb',
				second_name: 'Iphone 15 Pro Titanium 128 Gb Global',
				title: '',
				price: 41999,
				img: './products/p6.jpg',
			},
			{
				id: 'p7',
				count: 0,
				name: 'Apple iPhone 16 Pro Titanium 256 Gb',
				second_name: 'Iphone 16 Pro Titanium 256 Gb Global',
				title: '',
				price: 49999,
				img: './products/p7.jpg',
			},
			{
				id: 'p8',
				count: 0,
				name: 'Samsung Galaxy S24 Ultra Titanium 256 Gb',
				second_name: 'Samsung Galaxy S24 Ultra Titanium 256 Gb Global',
				title: '',
				price: 37499,
				img: './products/p8.jpg',
			},
			{
				id: 'p9',
				count: 0,
				name: 'Xiaomi 13 Ultra 512 Gb',
				second_name: 'Xiaomi 13 Ultra 512 Gb UA UCRF',
				title: '',
				price: 30999,
				img: './products/p9.jpg',
			},
			{
				id: 'p10',
				count: 0,
				name: 'Samsung Galaxy A16 SM-A165F',
				second_name: 'Samsung Galaxy A16 SM-A165F UA UCRF',
				title: '',
				price: 6599,
				img: './products/p10.jpg',
			},
			{
				id: 'p11',
				count: 0,
				name: 'Power Bank Baseus Bipow Digital Display 10000mAh',
				second_name: 'Power Bank Baseus Bipow Digital Display 10000mAh UA UCRF',
				title: '',
				price: 679,
				img: './products/p11.jpg',
			},
			{
				id: 'p12',
				count: 0,
				name: 'TWS Lenovo LivePods LP60 5.0 black',
				second_name: 'Lenovo LivePods LP60 5.0 black UA UCRF',
				title: '',
				price: 890,
				img: './products/p12.jpg',
			},
			{
				id: 'p13',
				count: 0,
				name: 'Bluetooth Stereo Panasonic RB-HF420BGE-K Black',
				second_name: 'Panasonic RB-HF420BGE-K Black UA UCRF',
				title: '',
				price: 1289,
				img: './products/p13.jpg',
			},
		],
		services: [
			{
				id: 'p14',
				count: 0,
				name: 'Поклейка скла',
				second_name: 'Поклейка скла до 6 дюймів',
				title: '',
				price: 199,
				img: './products/p14.jpg',
			},
			{
				id: 'p15',
				count: 0,
				name: 'Поклейка плівки',
				second_name: 'Поклейка плівки до 6 дюймів',
				title: '',
				price: 199,
				img: './products/p15.jpg',
			},
			{
				id: 'p16',
				count: 0,
				name: 'Налаштування Стандарт',
				second_name: 'Програмне забезпечення "Стандарт"',
				title: '',
				price: 999,
				img: './products/p16.jpg',
			},
			{
				id: 'p17',
				count: 0,
				name: 'Налаштування Преміум',
				second_name: 'Програмне забезпечення "Преміум"',
				title: '',
				price: 1999,
				img: './products/p16.jpg',
			},
			{
				id: 'p18',
				count: 0,
				name: 'Налаштування Ультра',
				second_name: 'Програмне забезпечення "Ультра"',
				title: '',
				price: 2999,
				img: './products/p16.jpg',
			},
			{
				id: 'p19',
				count: 0,
				name: 'Упаковка товару',
				second_name: 'Упаковка',
				title: '',
				price: 99,
				img: './products/p17.jpg',
			},
		],
	},
])
