import { ref } from 'vue'
export const PRODUCTS_DATA = ref([
	{
		id: 'p6',
		count: 0,
		name: 'Apple iPhone 15 Pro Titanium 128 Gb Global',
		title: '',
		price: 41999,
		img: './products/p6.jpg',
	},
	{
		id: 'p7',
		count: 0,
		name: 'Apple iPhone 16 Pro Titanium 256 Gb Global',
		title: '',
		price: 49999,
		img: './products/p7.jpg',
	},
	{
		id: 'p8',
		count: 0,
		name: 'Samsung Galaxy S24 Ultra Titanium Global',
		title: '',
		price: 37499,
		img: './products/p8.jpg',
	},
	{
		id: 'p9',
		count: 0,
		name: 'Xiaomi 13 Ultra 512 Gb Global UA UCRF',
		title: '',
		price: 30999,
		img: './products/p9.jpg',
	},
	{
		id: 'p10',
		count: 0,
		name: 'Samsung Galaxy A16 SM-A165F Global UA UCRF',
		title: '',
		price: 6599,
		img: './products/p10.jpg',
	},
	{
		id: 'p11',
		count: 0,
		name: 'Power Bank Baseus Bipow Digital Display 10000mAh',
		title: '',
		price: 679,
		img: './products/p11.jpg',
	},
	{
		id: 'p12',
		count: 0,
		name: 'TWS Lenovo LivePods LP60 5.0 black',
		title: '',
		price: 890,
		img: './products/p12.jpg',
	},
	{
		id: 'p13',
		count: 0,
		name: 'Bluetooth Stereo Panasonic RB-HF420BGE-K Black UA',
		title: '',
		price: 1289,
		img: './products/p13.jpg',
	},
])
