import { ref } from 'vue'

export const TABLE_DATA = ref([
	{
		id: 345286913,
		order: {
			order_status: 'Новий',
			contact_status: 'Не вдалося зв’язатися',
			pay_status: 'Не оплачено',
			pay_method: '',
			created_at: '08.08.2025 08:50',
			status_changed_at: '',
			source: 'Mail',
			source_utm: 'prom_site',
			manager: '',
			manager_comment: '',
		},
		customer: {
			name: 'Іван Іванович',
			phone: '+380671112233',
			email: 'ivan@example.com',
			comment: '',
		},
		sender: {
			name: '',
			phone: '',
		},
		recipient: {
			name: 'Оксана Іванова',
			phone: '+380671112234',
		},
		products: [
			{
				id: '2698',
				count: 1,
				count_name: 'шт',
				name: 'Samsung Galaxy S24 Ultra Titanium 256 Gb',
				second_name: 'Samsung Galaxy S24 Ultra Titanium 256 Gb Global',
				title:
					'6.8" Dynamic AMOLED 2X (120 Гц, QHD+), Snapdragon 8 Gen 3, 200 Мп (основна) + 50 Мп (теле 5x) + 12 Мп (ультраширока) + 10 Мп (теле 3x), S Pen, Titanium Frame, 5000 мАг, 45W зарядка, Android 14 (One UI 6.1), IP68',
				soft: 'Android 14',
				nfc: 'Так',
				wireless_charger: 'Так',
				sd_card: 'Ні',
				screen_diagonal: '6.8',
				display_type: 'OLED',
				refresh_rate: '120 Гц',
				sim_type: 'Nano SIM',
				sim_count: '1',
				waterproof: 'IP68',
				cpu: 'Snapdragon 8 Gen 3',
				battery_capacity: '4855 мАг',
				equipment:
					'Смартфон, Кабель USB-C, Інструмент для виймання SIM-картки, Керівництво',
				availability: 'В наявності',
				price: 37499,
				img: './products/p8.jpg',
				warehouse: [],
			},
		],

		additional_products: [],

		delivery: {
			delivery_date: '',
			service: '',
			delivery_method: '',
			delivery_payer: '',
			delivery_warehouse: '',
			item_description: '',
			assessed_value: '',
			width: '',
			height: '',
			length: '',
			weight: '',
			volumetric_weight: '',
			ttn: '',
			adress: 'Відділення №4',
			city: 'м. Харків',
			delivery_status: 'Доставлено',
			status_history: [
				{
					status: 'Замовлення отримано',
					date: '01/06/2025',
					time: '10:15',
					comment: 'Замовлення отримано від клієнта',
				},
				{
					status: 'Обробка замовлення',
					date: '01/06/2025',
					time: '11:30',
					comment: 'Замовлення передано на комплектацію',
				},
				{
					status: 'У дорозі',
					date: '02/06/2025',
					time: '08:30',
					comment: 'Замовлення прямує до відділення',
				},
				{
					status: 'Прибуло у відділення',
					date: '04/06/2025',
					time: '11:40',
					comment: 'Замовлення прибуло на відділення',
				},
				{
					status: 'Доставлено',
					date: '04/06/2025',
					time: '16:40',
					comment: 'Клієнт отримав замовлення',
				},
			],
			delivery_price: '',
		},
	},
	{
		id: 345286218,
		order: {
			order_status: 'Новий',
			contact_status: 'Не вдалося зв’язатися',
			pay_status: 'Не оплачено',
			pay_method: '',
			created_at: '08.08.2025 12:50',
			status_changed_at: '',
			source: 'Mail',
			source_utm: 'prom_ads',
			manager: '',
			manager_comment: '',
		},
		customer: {
			name: 'Петро Петрович',
			phone: '+380671113322',
			email: 'petro@example.com',
			comment: '',
		},
		sender: {
			name: '',
			phone: '',
		},
		recipient: {
			name: 'Марина Петрівна',
			phone: '+380671114456',
		},
		products: [
			{
				id: '5432',
				count: 1,
				count_name: 'шт',
				name: 'Apple iPhone 15 Pro Titanium 128 Gb',
				second_name: 'Iphone 15 Pro Titanium 128 Gb Global',
				title:
					'6,1" Super Retina XDR (120 Гц), A17 Pro, 48 Мп (основна) + 12 Мп (ультраширока) + 12 Мп (теле), титановий корпус, USB-C, Face ID, iOS 17, 5G, без адаптера в комплекті',
				soft: 'iOS 17',
				nfc: 'Так',
				wireless_charger: 'Так',
				sd_card: 'Ні',
				screen_diagonal: '6.1',
				display_type: 'OLED',
				refresh_rate: '120 Гц',
				sim_type: 'Nano SIM',
				sim_count: '1',
				waterproof: 'IP68',
				cpu: 'Apple A17 Pro',
				battery_capacity: '3274 мАг',
				equipment:
					'Смартфон, Кабель USB-C, Інструмент для виймання SIM-картки, Керівництво',
				availability: 'В наявності',
				price: 41999,
				img: './products/p6.jpg',
				warehouse: [],
			},
		],

		additional_products: [],

		delivery: {
			delivery_date: '',
			service: '',
			delivery_method: '',
			delivery_payer: '',
			delivery_warehouse: '',
			item_description: '',
			assessed_value: '',
			width: '',
			height: '',
			length: '',
			weight: '',
			volumetric_weight: '',
			ttn: '',
			adress: 'Відділення №2',
			city: 'м. Київ',
			delivery_status: 'Замовлення отримано',
			status_history: [
				{
					status: 'Замовлення отримано',
					date: '04/06/2025',
					time: '12:15',
					comment: 'Замовлення отримано від клієнта',
				},
			],
			delivery_price: '',
		},
	},
])
